"""add unique constraint on law_articles

Revision ID: 52779635ca3f
Revises: d17b6d6dc52f
Create Date: 2026-09-17 23:59:32.504249

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52779635ca3f'
down_revision: str | None = 'd17b6d6dc52f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_law_article', 'law_articles', ['law_id', 'article_no'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_law_article', 'law_articles', type_='unique')
    # ### end Alembic commands ###