"""init schema

Revision ID: d17b6d6dc52f
Revises: 
Create Date: 2026-09-17 13:49:16.470935

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd17b6d6dc52f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('issuing_org', sa.String(length=200), nullable=True),
    sa.Column('effective_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laws_category'), 'laws', ['category'], unique=False)
    op.create_index(op.f('ix_laws_code'), 'laws', ['code'], unique=True)
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_category'), 'standards', ['category'], unique=False)
    op.create_index(op.f('ix_standards_code'), 'standards', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('law_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('law_id', sa.Integer(), nullable=False),
    sa.Column('article_no', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('paragraph', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=20), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_articles_law_id'), 'law_articles', ['law_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('contract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_start_date', sa.Date(), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('contract_duration_days', sa.Integer(), nullable=True),
    sa.Column('owner_org', sa.String(length=200), nullable=True),
    sa.Column('design_org', sa.String(length=200), nullable=True),
    sa.Column('supervisor_org', sa.String(length=200), nullable=True),
    sa.Column('contractor_org', sa.String(length=200), nullable=True),
    sa.Column('contract_clauses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_table('standard_clauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('clause_no', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('behavior_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_clauses_is_mandatory'), 'standard_clauses', ['is_mandatory'], unique=False)
    op.create_index(op.f('ix_standard_clauses_standard_id'), 'standard_clauses', ['standard_id'], unique=False)
    op.create_table('behavior_standard_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('behavior_key', sa.String(length=100), nullable=False),
    sa.Column('behavior_description', sa.Text(), nullable=False),
    sa.Column('behavior_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clause_id', sa.Integer(), nullable=False),
    sa.Column('related_article_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('legal_consequence', sa.Text(), nullable=True),
    sa.Column('annotated_by', sa.String(length=50), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['standard_clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_article_id'], ['law_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_standard_mappings_behavior_key'), 'behavior_standard_mappings', ['behavior_key'], unique=False)
    op.create_index(op.f('ix_behavior_standard_mappings_clause_id'), 'behavior_standard_mappings', ['clause_id'], unique=False)
    op.create_index(op.f('ix_behavior_standard_mappings_risk_level'), 'behavior_standard_mappings', ['risk_level'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dispute_summary_user', sa.Text(), nullable=True),
    sa.Column('dispute_summary_ai', sa.Text(), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_project_id'), 'consultations', ['project_id'], unique=False)
    op.create_index(op.f('ix_consultations_scenario'), 'consultations', ['scenario'], unique=False)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.create_table('project_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('storage_provider', sa.String(length=20), nullable=False),
    sa.Column('parsed_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parse_status', sa.String(length=20), nullable=False),
    sa.Column('parse_error', sa.String(length=1000), nullable=True),
    sa.Column('document_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_documents_document_type'), 'project_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_project_documents_project_id'), 'project_documents', ['project_id'], unique=False)
    op.create_table('consultation_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_artifacts_consultation_id'), 'consultation_artifacts', ['consultation_id'], unique=False)
    op.create_table('consultation_conclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('fact_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('law_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('standard_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_chain', sa.Text(), nullable=True),
    sa.Column('counter_arguments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_conclusions_consultation_id'), 'consultation_conclusions', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_consultation_conclusions_level'), 'consultation_conclusions', ['level'], unique=False)
    op.create_table('consultation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('step_at_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_messages_consultation_id'), 'consultation_messages', ['consultation_id'], unique=False)
    op.create_table('consultation_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('fact_key', sa.String(length=100), nullable=False),
    sa.Column('fact_label', sa.String(length=200), nullable=False),
    sa.Column('fact_value', sa.Text(), nullable=False),
    sa.Column('fact_value_type', sa.String(length=20), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_message_id'], ['consultation_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_facts_consultation_id'), 'consultation_facts', ['consultation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_facts_consultation_id'), table_name='consultation_facts')
    op.drop_table('consultation_facts')
    op.drop_index(op.f('ix_consultation_messages_consultation_id'), table_name='consultation_messages')
    op.drop_table('consultation_messages')
    op.drop_index(op.f('ix_consultation_conclusions_level'), table_name='consultation_conclusions')
    op.drop_index(op.f('ix_consultation_conclusions_consultation_id'), table_name='consultation_conclusions')
    op.drop_table('consultation_conclusions')
    op.drop_index(op.f('ix_consultation_artifacts_consultation_id'), table_name='consultation_artifacts')
    op.drop_table('consultation_artifacts')
    op.drop_index(op.f('ix_project_documents_project_id'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_document_type'), table_name='project_documents')
    op.drop_table('project_documents')
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_scenario'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_project_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_behavior_standard_mappings_risk_level'), table_name='behavior_standard_mappings')
    op.drop_index(op.f('ix_behavior_standard_mappings_clause_id'), table_name='behavior_standard_mappings')
    op.drop_index(op.f('ix_behavior_standard_mappings_behavior_key'), table_name='behavior_standard_mappings')
    op.drop_table('behavior_standard_mappings')
    op.drop_index(op.f('ix_standard_clauses_standard_id'), table_name='standard_clauses')
    op.drop_index(op.f('ix_standard_clauses_is_mandatory'), table_name='standard_clauses')
    op.drop_table('standard_clauses')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_law_articles_law_id'), table_name='law_articles')
    op.drop_table('law_articles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_standards_code'), table_name='standards')
    op.drop_index(op.f('ix_standards_category'), table_name='standards')
    op.drop_table('standards')
    op.drop_index(op.f('ix_laws_code'), table_name='laws')
    op.drop_index(op.f('ix_laws_category'), table_name='laws')
    op.drop_table('laws')
    # ### end Alembic commands ###